# Generated by Django 2.2.4 on 2019-08-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('daily_time', models.TimeField(auto_now_add=True)),
                ('weekly_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
